# Generated by Django 4.0.2 on 2022-02-01 21:08

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('file', models.FileField(upload_to=contracts.models.Contract.get_upload_to, verbose_name='Archivo')),
            ],
        ),
    ]
