# Generated by Django 4.0.2 on 2022-02-01 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=128, verbose_name='POL')),
                ('destination', models.CharField(max_length=128, verbose_name='POD')),
                ('currency', models.CharField(max_length=128, verbose_name='Curr')),
                ('twenty', models.CharField(max_length=128, verbose_name='20’GP')),
                ('forty', models.CharField(max_length=128, verbose_name='40’GP')),
                ('fortyhc', models.CharField(max_length=128, verbose_name='40’HC')),
                ('fk_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Empresas')),
            ],
        ),
    ]
